info:
    id: compact_death_cause

ingredients:
    - id: deaths_datapoints
      dataset: open-numbers/ddf--ihme--global_burden_disease_deaths
      key: "cause, sex, age, location, year"
      value: "*"
    - id: incidence_datapoints
      dataset: open-numbers/ddf--ihme--global_burden_disease_cancer_incidence
      key: "cause, sex, age, location, year"
      value: "*"

cooking:
    datapoints:
        - procedure: filter
          ingredients:
              - deaths_datapoints
          result: deaths_datapoints-filtered
          options:
              item:
                  - deaths_rate
                  - deaths_number
              row:
                  cause:
                      $in:
                          - "429"
                          - "432"
                          - "441"
                          - "697"
                          - "298"
                          - "687"
                          - "417"
                          - "426"
                          - "345"
                          - "692"
                          - "724"
                          - "409"
                          - "700"
                          - "438"
                          - "414"
                          - "718"
                          - "689"
                          - "341"
                          - "332"
                          - "699"
                  age:
                      $in:
                          - "22"
                          - "27"
                          - "1"
                          - "6"
                          - "7"
                          - "8"
                          - "9"
                          - "10"
                          - "11"
                          - "12"
                          - "13"
                          - "14"
                          - "15"
                          - "16"
                          - "17"
                          - "18"
                          - "19"
                          - "20"
                          - "30"
                          - "31"
                          - "32"
                          - "235"
                          - "23"
        - procedure: filter
          ingredients:
              - incidence_datapoints
          options:
              item:
                  - incidence_number
                  - incidence_rate
              row:
                  cause:
                      $in:
                          - "429"
                          - "432"
                          - "441"
                          - "697"
                          - "298"
                          - "687"
                          - "417"
                          - "426"
                          - "345"
                          - "692"
                          - "724"
                          - "409"
                          - "700"
                          - "438"
                          - "414"
                          - "718"
                          - "689"
                          - "341"
                          - "332"
                          - "699"
                  age:
                      $in:
                          - "22"
                          - "27"
          result: incidence_datapoints-filtered

        - procedure: serve
          ingredients:
              - incidence_datapoints-filtered
              - deaths_datapoints-filtered
          options:
              split_datapoints_by:
                  - sex
